import os
import numpy as np
from tqdm import tqdm
import pandas as pd
import utils
from config import Config
from pathlib import Path
from sklearn.metrics.pairwise import cosine_similarity, cosine_distances
from matplotlib import pyplot as plt
from sklearn.decomposition import PCA

"""This module explores the embeddings generated by LLaVA"""

def check_similarity(x, y=None, pca=False):
    """Wide std
    Mean needs to be close to 0, std close to 1.
    High similarity count should be much low then: n(n-1)/2
    """
    similarity_matrix = cosine_similarity(x)

    # Set diagonal to 0 (self-similarity)
    np.fill_diagonal(similarity_matrix, 0)

    # High similarity count (> 0.95 means almost identical)
    high_sim_count_unique = (np.sum(similarity_matrix > 0.95)) / 2
    print(f"Number of embedding pairs with cosine similarity > 0.95: {high_sim_count_unique}")

    # Mean and std
    print("Mean embedding:", np.mean(x, axis=0)[:5])
    print("Std of embeddings:", np.std(x, axis=0)[:5])

    dists = cosine_distances(x)
    np.fill_diagonal(dists, np.nan)

    plt.hist(dists[~np.isnan(dists)].flatten(), bins=100)
    plt.title("Histogram of Pairwise Cosine Distances")
    plt.xlabel("Cosine Distance")
    plt.ylabel("Frequency")
    plt.show()

    if pca:
        pca = PCA()
        pca.fit(x)
        explained_variance_ratio = pca.explained_variance_ratio_

        plt.plot(np.cumsum(explained_variance_ratio))
        plt.title("Cumulative Explained Variance by PCA")
        plt.xlabel("Number of Components")
        plt.ylabel("Cumulative Variance")
        plt.grid(True)
        plt.show()

    if y is not None:
        y = np.array(y)
        n = len(y)
        label_matrix = y[:, None] == y[None, :]  # (n, n) matrix where (i,j)=True if same class
        mask_intra = np.triu(label_matrix, k=1)
        mask_inter = np.triu(~label_matrix, k=1)

        intra_dists = dists[mask_intra]
        inter_dists = dists[mask_inter]

        # Plot distributions
        plt.hist(intra_dists, bins=50, alpha=0.6, label='Intra-class', color='green', density=True)
        plt.hist(inter_dists, bins=50, alpha=0.6, label='Inter-class', color='red', density=True)
        plt.title("Intra-class vs Inter-class Cosine Distances")
        plt.xlabel("Cosine Distance")
        plt.ylabel("Density")
        plt.legend()
        plt.grid(True)
        plt.show()

        # Print stats
        print(f"Mean intra-class distance: {np.mean(intra_dists):.4f}")
        print(f"Mean inter-class distance: {np.mean(inter_dists):.4f}")
        print(f"Separation gap: {np.mean(inter_dists) - np.mean(intra_dists):.4f}")

config_wrapper = Config()

# Directory containing embedding files
base_dir = Path(__file__).resolve().parent.parent
embedding_dir = os.path.join(base_dir, "ClassifiersTests","3","train")
embeddings_metadata = pd.read_csv(os.path.join(embedding_dir, "embeddings_metadata.csv"))

# List to store embeddings
embeddings = []
labels = []

# Iterate through the directory
for _, row in tqdm(embeddings_metadata.iterrows(), desc="Loading embeddings"):
    file_path = row["embedding_path"]
    label = row["label"]
    embedding = np.load(file_path)
    embeddings.append(embedding)
    labels.append(label)
X = np.array(embeddings)
y = np.array(labels)

check_similarity(X, y)
utils.plot_tsne(X,y, perplexity=70)
utils.plot_umap(X,y)
utils.plot_isomap(X,y)
